# Generated by Django 5.2 on 2026-08-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolucoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('principio_ativo', models.CharField(blank=True, max_length=150)),
                ('apresentacoes', models.TextField(blank=True, help_text='Ex.: 500mg comprimido; 20mg/mL gotas')),
                ('uso_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes foi prescrito (favoritos)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-uso_count', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('origem_sugestao', models.BooleanField(default=False, help_text='Gerada a partir do motor de sugestões')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receituarios', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(help_text='Ex.: "20mg" ou "1 comprimido 500mg"', max_length=100)),
                ('quantidade', models.CharField(blank=True, help_text='Ex.: "30 comprimidos"', max_length=50)),
                ('posologia', models.TextField(help_text='Ex.: "1 cp de 12/12h por 7 dias"')),
                ('observacoes_item', models.CharField(blank=True, max_length=200)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receituario.medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receituario.receita')),
            ],
        ),
    ]
