# Generated by Django 5.1.7 on 2025-04-02 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=16)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], max_length=24)),
                ('estadocivil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viuvo(a)', 'Viuvo(a)')], max_length=25)),
                ('datanascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=120)),
                ('profissao', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='fotos')),
                ('evolucao', models.TextField()),
                ('data_criacao', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('qp', models.CharField(max_length=125)),
                ('hma', models.CharField(max_length=125)),
                ('hpp', models.CharField(max_length=125)),
                ('antecedentepf', models.CharField(max_length=120)),
                ('exame_fisico', models.CharField(max_length=88)),
                ('exames_complementares', models.CharField(max_length=80)),
                ('diagnostico', models.CharField(max_length=80)),
                ('plano_terapeutico', models.CharField(max_length=80)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.pacientes')),
            ],
        ),
    ]
