# Generated by Django 5.1.7 on 2025-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
