# Generated by Django 5.1.7 on 2025-04-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
