# Generated by Django 5.2 on 2025-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0005_alter_evolucao_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
