# Generated by Django 5.2 on 2025-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0006_alter_evolucao_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='data',
            new_name='data_dadospaciente',
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
