# Generated by Django 5.2.1 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0007_rename_data_dadospaciente_data_dadospaciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
