# Generated by Django 5.2 on 2026-01-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0008_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='antecedentepf',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='diagnostico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='exame_fisico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='exames_complementares',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='hma',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='hpp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='plano_terapeutico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='qp',
            field=models.CharField(max_length=200),
        ),
    ]
