# Generated by Django 5.2 on 2026-02-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0009_alter_dadospaciente_antecedentepf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evolucao',
        ),
    ]
