# Generated by Django 5.2 on 2026-08-25 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolucoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAtestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('texto_template', models.TextField(help_text='Use {{variavel}} para campos dinâmicos. Variáveis: paciente, data_hoje, medico, periodo, dias, cid, local, clinica')),
                ('requer_dias', models.BooleanField(default=False)),
                ('requer_periodo', models.BooleanField(default=False)),
                ('requer_cid', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, help_text='Código CID-10, se aplicável', max_length=10)),
                ('periodo', models.CharField(blank=True, help_text="Ex.: 'de 18/02 a 25/02/2026'", max_length=100)),
                ('dias_afastamento', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('texto_final', models.TextField(blank=True)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atestados.modeloatestado')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
