# Generated by Django 5.2 on 2026-02-18 13:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolucoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField()),
                ('periodo', models.CharField(max_length=100)),
                ('dias_afastamento', models.PositiveIntegerField(default=0)),
                ('data_emissao', models.DateField(default=datetime.date.today)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExameAnexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='exames/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_anexados', to='evolucoes.evolucao')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exames_solicitados', models.TextField()),
                ('justificativa_clinica', models.TextField(blank=True)),
                ('data_pedido', models.DateField(default=datetime.date.today)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_exames', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('posologia', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_emissao', models.DateField(default=datetime.date.today)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receituarios', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
