# Generated by Django 5.2 on 2026-02-18 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_medicamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receituario',
            old_name='observacoes',
            new_name='observacoes_gerais',
        ),
        migrations.RemoveField(
            model_name='receituario',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='receituario',
            name='posologia',
        ),
        migrations.AlterField(
            model_name='receituario',
            name='data_emissao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReceituarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=100)),
                ('quantidade', models.CharField(blank=True, max_length=50)),
                ('posologia', models.TextField()),
                ('observacoes_item', models.CharField(blank=True, max_length=200)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.medicamento')),
                ('receituario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='documentos.receituario')),
            ],
        ),
    ]
