# Generated by Django 5.2.1 on 2025-07-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='confirmado',
            field=models.BooleanField(default=True, verbose_name='Confirmado'),
        ),
    ]
