# Generated by Django 5.2.1 on 2025-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_consulta_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
