# Generated by Django 5.2 on 2026-08-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exames', '0001_initial'),
        ('prontuario', '0010_delete_evolucao'),
        ('receituario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cid', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Condições',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceitou_sugestao', models.BooleanField(default=False, help_text='O médico aceitou a principal sugestão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.pacientes')),
                ('condicao_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sugestoes.condicao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=True, help_text='Médico confirmou este sintoma')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugestoes.analiseclinica')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugestoes.sintoma')),
            ],
            options={
                'unique_together': {('analise', 'sintoma')},
            },
        ),
        migrations.AddField(
            model_name='analiseclinica',
            name='sintomas',
            field=models.ManyToManyField(through='sugestoes.AnaliseSintoma', to='sugestoes.sintoma'),
        ),
        migrations.CreateModel(
            name='CondicaoExameSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_sugeridos', to='sugestoes.condicao')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exames.exame')),
            ],
            options={
                'verbose_name_plural': 'Exames sugeridos por condição',
                'unique_together': {('condicao', 'exame')},
            },
        ),
        migrations.CreateModel(
            name='CondicaoMedicamentoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
                ('posologia_sugerida', models.CharField(blank=True, help_text='Posologia padrão sugerida ao médico', max_length=200)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_sugeridos', to='sugestoes.condicao')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receituario.medicamento')),
            ],
            options={
                'verbose_name_plural': 'Medicamentos sugeridos por condição',
                'unique_together': {('condicao', 'medicamento')},
            },
        ),
        migrations.CreateModel(
            name='SintomaCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0, help_text='Relevância deste sintoma para a condição (>= 0.05)')),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='sugestoes.condicao')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='sugestoes.sintoma')),
            ],
            options={
                'unique_together': {('sintoma', 'condicao')},
            },
        ),
    ]
