# Generated by Django 5.2 on 2026-02-18 13:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prontuario', '0010_delete_evolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='fotos')),
                ('evolucao', models.TextField()),
                ('data_criacao', models.DateField(default=datetime.date.today)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.pacientes')),
            ],
        ),
    ]
