# Generated by Django 5.2 on 2026-08-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolucoes', '0001_initial'),
        ('prontuario', '0010_delete_evolucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('codigo_tuss', models.CharField(blank=True, max_length=20)),
                ('categoria', models.CharField(choices=[('laboratorial', 'Laboratorial'), ('imagem', 'Imagem'), ('procedimento', 'Procedimento'), ('outro', 'Outro')], default='laboratorial', max_length=20)),
                ('preparo', models.TextField(blank=True, help_text='Orientações de preparo para o paciente')),
                ('uso_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes foi pedido (favoritos)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Exames',
                'ordering': ['-uso_count', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa_clinica', models.TextField(blank=True)),
                ('origem_sugestao', models.BooleanField(default=False, help_text='Gerado a partir do motor de sugestões')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('evolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_exames', to='evolucoes.evolucao')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucoes', models.CharField(blank=True, max_length=200)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exames.exame')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='exames.pedidoexame')),
            ],
            options={
                'unique_together': {('pedido', 'exame')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='resultados/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem'), ('outro', 'Outro')], default='pdf', max_length=10)),
                ('texto_extraido', models.TextField(blank=True)),
                ('leitura_ok', models.BooleanField(default=False, help_text='Texto extraído e valores interpretados')),
                ('resumo_leitura', models.TextField(blank=True, help_text='Resumo gerado automaticamente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exames.itempedidoexame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_exames', to='prontuario.pacientes')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analito', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('referencia_min', models.FloatField(blank=True, null=True)),
                ('referencia_max', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('alto', 'Alto'), ('baixo', 'Baixo'), ('nao_avaliado', 'Sem referência')], default='nao_avaliado', max_length=15)),
                ('orientacao', models.CharField(blank=True, max_length=250)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='exames.resultadoexame')),
            ],
            options={
                'verbose_name_plural': 'Medições do resultado',
            },
        ),
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analito', models.CharField(help_text='Ex.: Hemoglobina, Glicemia', max_length=100)),
                ('padrao_busca', models.CharField(help_text='Regex que captura o valor no PDF (grupo 1 = número)', max_length=300)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('ambos', 'Ambos'), ('M', 'Masculino'), ('F', 'Feminino')], default='ambos', max_length=5)),
                ('orientacao_alto', models.CharField(blank=True, max_length=250)),
                ('orientacao_baixo', models.CharField(blank=True, max_length=250)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='exames.exame')),
            ],
            options={
                'verbose_name_plural': 'Valores de referência',
            },
        ),
    ]
