# Generated by Django 5.2.1 on 2025-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='eh_teste_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('teste', 'Teste Gratuito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
