# Generated by Django 5.1.7 on 2025-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativacao',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
