# Generated by Django 5.1.7 on 2025-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_perfilprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='nomeclinica',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
