# Generated by Django 5.2.1 on 2025-07-01 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('automatico', models.BooleanField(default=False)),
                ('enviar_email', models.BooleanField(default=True)),
                ('enviar_whatsapp', models.BooleanField(default=False)),
                ('primeira_vez_login', models.BooleanField(default=False)),
                ('prioridade', models.CharField(choices=[('info', 'Informativo'), ('alerta', 'Alerta'), ('erro', 'Erro')], default='info', max_length=10)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='avisos_direcionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aviso', 'usuario')},
            },
        ),
    ]
